Code refactoring
Mazel-Tovr/kotlin-app pull request #1
Opened 2020-11-13 12:58 UTC by Mazel-Tovr

Chang casual collections to kotlin.immutable fix some issues with it , to make it work , refactor business layer and controllers (like Igor(b)) said , and some add practice with ds and coroutines

2020-11-13 13:04 UTC, Mazel-Tovr commented
там самыйе главыне изменения в "add more refactoring"

2020-11-16 10:01 UTC, LikhanovMaxim requested changes

2020-11-16 10:01 UTC, LikhanovMaxim commented on README.md
> +| ```http://your-host/{controller}/getall``` | GET | get all entities from db|
не надо использовать 'get' в а АПИ, 5-ый пункт https://kb.epam.com/display/EPMDJ/Code+Conventions

2020-11-16 10:01 UTC, LikhanovMaxim commented on README.md
> +| ```http://your-host/{controller}/getall``` | PUT | edit entity (entity should be in req body)|
getall - получить 
PUT - вставить
edit entity - изменить

несогласованность, надо править, чтобы не было консернов
проверь всю АПИ

2020-11-16 10:01 UTC, LikhanovMaxim commented on README.md
> +# simple-kotlin-app
все коммиты объедини в один коммит и форс пушни

2020-11-16 10:01 UTC, LikhanovMaxim commented on src/main/kotlin/com/epam/kotlinapp/crud/business/UserService.kt
> +//        return user ?: throw DataException("User couldn't be created")
удали, если это не нужно

2020-11-16 10:01 UTC, LikhanovMaxim commented on src/main/kotlin/com/epam/kotlinapp/crud/controllers/ProductController.kt
>  }
поправь перенос строки

2020-11-16 10:01 UTC, LikhanovMaxim commented on src/main/kotlin/com/epam/kotlinapp/crud/controllers/ProductGroupController.kt
>  }
перенос строки

2020-11-16 10:47 UTC, Mazel-Tovr commented on README.md
> +# simple-kotlin-app
done

2020-11-16 10:49 UTC, LikhanovMaxim commented on README.md
> +| ```http://your-host/{controller}/getall``` | PUT | edit entity (entity should be in req body)|
разверни дрилл, зайди в свагер и посмотри как выглядит АПИ, 
PUT | edit entity (entity should be in req body)| --- нужно передавать ид

классы с большрй буквы: class user

2020-11-18 13:43 UTC, merged